### ISSUE TITLE
A total number of 6 errors in the RichEditor.tsx file

### ISSUE THREAD

**Issue by malikmouhiidine** [PacktPublishing/Full-Stack-React-TypeScript-and-Node#15]
I 'am currently stuck at chapter 12 with this huge number of errors and because of my limited knowledge about slate and overall typescript I couldn't fix any of them so I'll appreciate some help and I'm sure this will help other future readers.

P.S: I didn't edit one line of code from how it is in the repo.

screenshot's :
![image](https://user-images.githubusercontent.com/73129654/125839935-c9b99fed-b848-4ce8-92f6-a8510e9c8486.png)
![image](https://user-images.githubusercontent.com/73129654/125839969-684f45d1-311f-40c1-a846-22fbb02230f9.png)
![image](https://user-images.githubusercontent.com/73129654/125840020-0cb46a7b-d8c5-4973-a875-9f140d50cacf.png)
![image](https://user-images.githubusercontent.com/73129654/125840048-30adc3de-2f39-4199-bc9c-d235e3949c8b.png)
![image](https://user-images.githubusercontent.com/73129654/125840070-a39457b3-ef82-4d4d-9f75-38eacb56ef51.png)
![image](https://user-images.githubusercontent.com/73129654/125840108-374ef7d5-1a54-4977-857d-2f960431f813.png)
[source code from the repo](https://github.com/PacktPublishing/Full-Stack-React-TypeScript-and-Node/blob/master/Chap12/super-forum-client/src/components/editor/RichEditor.tsx)

**Comment by jsoneaday** [comment]
There is no issue in the code. Slatejs has been updated significantly since the book was released.

Please download the exact dependency versions given in the package.json file and everything will work.

**Comment by malikmouhiidine** [comment]
Got it thanks!
