### ISSUE TITLE
Chapter 5 Update Greeting.tsx to include the getDerivedStateFromProps

### ISSUE THREAD

**Issue by armenic** [PacktPublishing/Full-Stack-React-TypeScript-and-Node#5]
Dear Author,
There is an issue in the following snippet of code. I think there should be also `GreetingState` type declaration, otherwise it fails.

```tsx
 React.Component<GreetingProps> {

    constructor(props: GreetingProps){
```

**Comment by mikerourke** [comment]
Hi @armenic, I was the technical reviewer on this book and I'm helping out with issues. I'll let the publisher know about the issue. It looks like the [code in this repo is correct](https://github.com/PacktPublishing/Full-Stack-React-TypeScript-and-Node/blob/7e17391e275dfe226cbec8d05d5719f137185482/Chap5/class-components/src/Greeting.tsx#L10), but the book needs to be updated. Thanks for bringing this to our attention!

**Comment by jsoneaday** [comment]
Hello @armenic, I am the author of the book, you are correct this is an error in the book. My apologies, without the type GreetingState an error occurs in the returned JSX since this.state.message no longer exists. Thank you for spotting this issue and letting us know.

`return <div>
            {this.state.message}
        </div>;`
