### ISSUE TITLE
Chapter 6: Mocking with jest.fn

### ISSUE THREAD

**Issue by armenic** [PacktPublishing/Full-Stack-React-TypeScript-and-Node#6]
Dear Author,
In `Chapter 6: Mocking with jest.fn` I think it is better to update the snippet with the following:

```
return userByName ? userByName.name : "Unknown name";
```
Otherwise when it renders the HTML shows `[Objec object]` for known names and `undefined` for unknowns.

**Comment by jsoneaday** [comment]
Sorry maybe I'm looking at the wrong section, but it appears you are referring to the function getUserFullname? Well when I run the app and enter a username, not full name, like for example bret or antonette my page loads with the appropriate data. I am not seeing [Object object]. I also was able to run all the tests successfully. None failed for me. Could you tell me the specific file and line you are referring to? Thanks.

![image](https://user-images.githubusercontent.com/1474935/106615205-32386f80-653a-11eb-805e-e3c87f4939f8.png)

**Comment by armenic** [comment]
thanks @jsoneaday, I was refereeing to the book on Oreilly. I guess one needs to use the code from this repository rather than copying from the book. On the other hand when I follows the flow of the book and does incremental updates of the code then the issue comes up. Please feel free to close the issue.
